"""empty message

Revision ID: 09b2e98add51
Revises: 35552f763de1
Create Date: 2019-04-02 09:43:08.095593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09b2e98add51'
down_revision = '35552f763de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banner_add_time'), 'banner', ['add_time'], unique=False)
    op.drop_index('ix_preview_add_time', table_name='preview')
    op.drop_index('title', table_name='preview')
    op.drop_table('preview')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preview',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('logo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('add_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('title', 'preview', ['title'], unique=True)
    op.create_index('ix_preview_add_time', 'preview', ['add_time'], unique=False)
    op.drop_index(op.f('ix_banner_add_time'), table_name='banner')
    op.drop_table('banner')
    # ### end Alembic commands ###
