"""empty message

Revision ID: 1e09b951534c
Revises: 946a1c6caeef
Create Date: 2019-03-28 18:07:23.670996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e09b951534c'
down_revision = '946a1c6caeef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.drop_constraint('comment_ibfk_2', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('movie_col_ibfk_2', 'movie_col', type_='foreignkey')
    op.drop_constraint('movie_col_ibfk_1', 'movie_col', type_='foreignkey')
    op.create_foreign_key(None, 'movie_col', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movie_col', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie_col', type_='foreignkey')
    op.drop_constraint(None, 'movie_col', type_='foreignkey')
    op.create_foreign_key('movie_col_ibfk_1', 'movie_col', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key('movie_col_ibfk_2', 'movie_col', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_2', 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key('comment_ibfk_1', 'comment', 'movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###
