"""empty message

Revision ID: 6852ccfa3573
Revises: 09b2e98add51
Create Date: 2019-04-02 23:09:43.542403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6852ccfa3573'
down_revision = '09b2e98add51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('collect_num', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'collect_num')
    # ### end Alembic commands ###
