"""empty message

Revision ID: 8b99528850ff
Revises: e09ab92dab4c
Create Date: 2019-05-26 22:24:04.221608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b99528850ff'
down_revision = 'e09ab92dab4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_ibfk_1', 'admin', type_='foreignkey')
    op.create_foreign_key(None, 'admin', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('admin_log_ibfk_1', 'admin_log', type_='foreignkey')
    op.create_foreign_key(None, 'admin_log', 'admin', ['admin_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('operation_log_ibfk_1', 'operation_log', type_='foreignkey')
    op.create_foreign_key(None, 'operation_log', 'admin', ['admin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operation_log', type_='foreignkey')
    op.create_foreign_key('operation_log_ibfk_1', 'operation_log', 'admin', ['admin_id'], ['id'])
    op.drop_constraint(None, 'admin_log', type_='foreignkey')
    op.create_foreign_key('admin_log_ibfk_1', 'admin_log', 'admin', ['admin_id'], ['id'])
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.create_foreign_key('admin_ibfk_1', 'admin', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###
