"""empty message

Revision ID: 946a1c6caeef
Revises: 73cd6071ff0b
Create Date: 2019-03-28 14:52:43.574596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946a1c6caeef'
down_revision = '73cd6071ff0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movie_ibfk_1', 'movie', type_='foreignkey')
    op.create_foreign_key(None, 'movie', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.create_foreign_key('movie_ibfk_1', 'movie', 'tag', ['tag_id'], ['id'])
    # ### end Alembic commands ###
